<a href="https://colab.research.google.com/github/RPJ123/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np #numerical python

#arrray collection of data with same datatype(Homogenious)


a=np.array([1,2,3.0,4]) #in array the data type is homogeneious
print(a)

[1. 2. 3. 4.]


In [4]:

a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [5]:
#slicing forward slicing backward slicing


b=np.array([1,2,3,4,5])

print(b[0:2])
print(b[-1:-3:-1])
print(b[3:])
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [6]:
#dimension

a=np.array([0,2,3,4,5])#one dimension
b=np.array([[1,2],[3,4]]) #two dimnension ->if there are two square brackets within the brackets

a.ndim  #ndimension   #if dimension=1 -> vector

b.ndim #if dimension==2 -> matrix

print(b)

b.shape  #to identify the shape -> row*column


[[1 2]
 [3 4]]


(2, 2)

3 dimension array is called tensor

In [7]:
#create a 2*2 matrix  [2,3],[4,5]


c=np.array([[2,3],[4,5]])
c.ndim
print(c)
print(c.shape)
print(c.ndim)  #to find which dimension



print(c.size)# to find total number of elements

[[2 3]
 [4 5]]
(2, 2)
2
4


In [8]:
#creaate a two*three  matrix


d=np.array([[2,3,4],[4,5,6]])
d.ndim
print(d)

print(d.shape)

print(d.ndim)

print(d.size)

[[2 3 4]
 [4 5 6]]
(2, 3)
2
6


In [9]:
#create a 4*2 matrix


e=np.array([[2,3],[4,5],[5,6],[6,7]])

print(e)

print(e.shape)

print(e.ndim)

print(e.size)


[[2 3]
 [4 5]
 [5 6]
 [6 7]]
(4, 2)
2
8


In [10]:
#create a 4*4 matrix

g=np.array([[2,3,4,5],[4,5,6,7],[2,3,4,5],[2,4,5,6]])
print(g)

print(g.shape)

print(g.ndim)

print(g.size)

[[2 3 4 5]
 [4 5 6 7]
 [2 3 4 5]
 [2 4 5 6]]
(4, 4)
2
16


FOR A MATRIX TEH DIMENSION IS ALWAYS 2


In [11]:
g[0]

array([2, 3, 4, 5])

In [12]:
g[:,0]

array([2, 4, 2, 2])

In [13]:
g[2,2]

np.int64(4)

In [14]:
g[3,2:]

array([5, 6])

In [15]:
g[2:,2:]

array([[4, 5],
       [5, 6]])

In [16]:
g[0:3,2:]

array([[4, 5],
       [6, 7],
       [4, 5]])

In [17]:
g[0:,2]

array([4, 6, 4, 5])

In [18]:
#zero matrix


z=np.zeros([3,3,3])
print(z)  #by default it is float :it canbe changed into int or complex

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [19]:

z=np.zeros([3,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
z=np.zeros([3,3,3],dtype=int)
print(z)  #rgb  images are shown in this method

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [21]:
#create two 2*2 matrix

a=np.array([[2,3],[4,5]])

b=np.array([[6,7],[3,4]])


print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [3 4]]


In [22]:
print(a+b)

print(a-b)

[[ 8 10]
 [ 7  9]]
[[-4 -4]
 [ 1  1]]


print(a*b) #not matrix multiplication


In [23]:



print(a@b) #for matrix multiplication

print(a.dot(b)) #for matrix multiplication

[[21 26]
 [39 48]]
[[21 26]
 [39 48]]


In [24]:
print(a/b)

[[0.33333333 0.42857143]
 [1.33333333 1.25      ]]


MAGIC FUNCTIONS   

__add__,__str__



In [25]:
#FULL MATRIX

z=np.full([3,3],5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
#create 3*4 matrix with value 9 and datatype complex
z=np.full([3,4],9,dtype=complex)
print(z)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [27]:
#identity matrix

z=np.identity(3,dtype=int)  #here only 3 is given as input as for iedntity matrix it should be square

a=np.eye(3) #another method for identity
print(z)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#create a 4*4 matrix



d=np.array([[2,3,4,5],[4,5,6,7],[9,8,7,4],[2,5,3,4]])
print(d)



print(d.size)

[[2 3 4 5]
 [4 5 6 7]
 [9 8 7 4]
 [2 5 3 4]]
16


In [29]:
#reshape
a=d.reshape(8,2)
print(a)

[[2 3]
 [4 5]
 [4 5]
 [6 7]
 [9 8]
 [7 4]
 [2 5]
 [3 4]]


In [30]:
#arange

a=np.arange(1,10,2)
print(a)


[1 3 5 7 9]


In [31]:
#create a 5*2 matrix using arange

b=np.arange(1,11).reshape(5,2)
print(b)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [32]:
#create a 3*3 matrix with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
print(a)

[[2.5 3.6 3.5]
 [1.5 1.1 6.5]
 [7.1 2.5 7.1]]


In [33]:
#FLOOR


z=np.floor(a)
print(z)

[[2. 3. 3.]
 [1. 1. 6.]
 [7. 2. 7.]]


In [34]:
d=np.ceil(a)

print(d)

[[3. 4. 4.]
 [2. 2. 7.]
 [8. 3. 8.]]


In [35]:
e=np.round(a)
print(z)

[[2. 3. 3.]
 [1. 1. 6.]
 [7. 2. 7.]]


In [36]:
#create a 3*3 matrix

g=np.arange(1,10).reshape(3,3)
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
a.max() #max in the entire matrix

np.float64(7.1)

In [38]:
a.max(axis=1) #to find max value in each row

array([3.6, 6.5, 7.1])

IN NUMPY    AXIS=1 -> ROW
            AXIS=0 -> COLUMN

IN PANDAS  AXIS=1 -> COLUMN
           AXIS=0 -> ROW

In [39]:
a.max(axis=0) #to find max value in each column

array([7.1, 3.6, 7.1])

In [40]:
a.min(axis=0)

array([1.5, 1.1, 3.5])

In [41]:
a.min(axis=1)


array([2.5, 1.1, 2.5])

In [42]:
a.min()

np.float64(1.1)

In [43]:
a.sum()

np.float64(35.4)

In [44]:
a.sum(axis=1)

array([ 9.6,  9.1, 16.7])

In [45]:
a.sum(axis=0)  #column

array([11.1,  7.2, 17.1])

In [46]:
np.sqrt(a) #to return square root

array([[1.58113883, 1.8973666 , 1.87082869],
       [1.22474487, 1.04880885, 2.54950976],
       [2.66458252, 1.58113883, 2.66458252]])

In [48]:
np.sin(a)

array([[ 0.59847214, -0.44252044, -0.35078323],
       [ 0.99749499,  0.89120736,  0.21511999],
       [ 0.72896904,  0.59847214,  0.72896904]])

In [49]:
np.cos(a)

array([[-0.80114362, -0.89675842, -0.93645669],
       [ 0.0707372 ,  0.45359612,  0.97658763],
       [ 0.68454667, -0.80114362,  0.68454667]])

In [50]:
a.flatten() #to  onvert any array to one dimension

array([2.5, 3.6, 3.5, 1.5, 1.1, 6.5, 7.1, 2.5, 7.1])

In [53]:
#sort create a 3*3 array sort

a=np.array([[2,3,5],[4,9,2],[5,4,3]])
a.ndim
print(a)
b=np.sort(a,axis=0)
print(b)

[[2 3 5]
 [4 9 2]
 [5 4 3]]
[[2 3 2]
 [4 4 3]
 [5 9 5]]


In [55]:
#sorting based on indexing

c=np.argsort(a,axis=1)
print(c)



[[0 1 2]
 [2 0 1]
 [2 1 0]]
